### ISSUE TITLE
Multiple Consoles 0.1.5

### ISSUE THREAD

**Issue by EuropaSteve** [pilotso11/fc-macros#6] opened 2022-03-10 04:13 UTC
When run in Pycharm I get multiple consoles
[fcmacros.log](https://github.com/pilotso11/fc-macros/files/8220231/fcmacros.log)
.

**Comment by pilotso11** [comment] 2022-03-10 06:25
Looks like it’s loading itself four times.  Ouch.   Will need to investigate that.

**Comment by pilotso11** [comment] 2022-03-10 23:16
Reproduced by running fcmacros.py directly instead of main.py which is what pyinstaller runs.  Resolved in 0.1.6

**Closed** 2022-03-13 15:45 UTC
